import 'dart:convert';
import '../../../core/domain/entities/transaction.dart';
import '../../analytics/domain/entities/analytics_summary.dart';
import '../domain/entities/report_config.dart';

class ExportEngine {
  static String generateCsv({
    required AnalyticsSummary summary,
    required List<TransactionEntity> transactions,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('ID,Date,Description,Amount,Type,Status,Category,Tags');

    for (final tx in transactions) {
      buffer.writeln(
        '"${tx.id}","${tx.date.toIso8601String()}","${tx.description.replaceAll('"', '""')}",${tx.amount},"${tx.type.name}","${tx.status.name}","${tx.categoryId ?? ''}","${tx.tags.join(';')}"',
      );
    }
    return buffer.toString();
  }

  static String generateJson({
    required AnalyticsSummary summary,
    required List<TransactionEntity> transactions,
  }) {
    final Map<String, dynamic> data = {
      'summary': {
        'totalIncome': summary.totalIncome,
        'totalExpenses': summary.totalExpenses,
        'netSavings': summary.netSavings,
        'savingsRate': summary.savingsRate,
        'avgDailySpending': summary.avgDailySpending,
        'topCategory': summary.topCategoryName,
        'transactionCount': summary.totalTransactionCount,
      },
      'transactions': transactions
          .map((t) => {
                'id': t.id,
                'date': t.date.toIso8601String(),
                'description': t.description,
                'amount': t.amount,
                'type': t.type.name,
                'status': t.status.name,
                'categoryId': t.categoryId,
                'tags': t.tags,
              })
          .toList(),
    };

    return const JsonEncoder.withIndent('  ').convert(data);
  }

  static String generateMarkdown({
    required ReportConfig config,
    required AnalyticsSummary summary,
    required List<TransactionEntity> transactions,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('# ${config.title}');
    buffer.writeln('*Generated by Monetra — Offline. Private. Yours.*\n');
    buffer.writeln('## Financial Summary');
    buffer.writeln(
        '- **Total Income:** \$${summary.totalIncome.toStringAsFixed(2)}');
    buffer.writeln(
        '- **Total Expenses:** \$${summary.totalExpenses.toStringAsFixed(2)}');
    buffer.writeln(
        '- **Net Savings:** \$${summary.netSavings.toStringAsFixed(2)} (${summary.savingsRate.toStringAsFixed(1)}%)');
    buffer.writeln(
        '- **Top Spending Category:** ${summary.topCategoryName} (\$${summary.topCategoryAmount.toStringAsFixed(2)})\n');
    buffer.writeln('## Transaction Details (${transactions.length} Records)\n');
    buffer.writeln('| Date | Description | Type | Amount |');
    buffer.writeln('| --- | --- | --- | --- |');

    for (final tx in transactions.take(100)) {
      final dateStr = '${tx.date.day}/${tx.date.month}/${tx.date.year}';
      buffer.writeln(
          '| $dateStr | ${tx.description} | ${tx.type.name.toUpperCase()} | \$${tx.amount.toStringAsFixed(2)} |');
    }

    return buffer.toString();
  }

  static String generateHtml({
    required ReportConfig config,
    required AnalyticsSummary summary,
    required List<TransactionEntity> transactions,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('<!DOCTYPE html><html><head><title>${config.title}</title>');
    buffer.writeln(
        '<style>body{font-family:sans-serif;padding:20px;} table{width:100%;border-collapse:collapse;} th,td{border:1px solid #ccc;padding:8px;text-align:left;} th{background:#f4f4f4;}</style>');
    buffer.writeln('</head><body>');
    buffer.writeln('<h1>${config.title}</h1>');
    buffer.writeln(
        '<p><strong>Total Income:</strong> \$${summary.totalIncome.toStringAsFixed(2)} | <strong>Total Expenses:</strong> \$${summary.totalExpenses.toStringAsFixed(2)}</p>');
    buffer.writeln(
        '<table><tr><th>Date</th><th>Description</th><th>Amount</th></tr>');

    for (final tx in transactions.take(50)) {
      final dateStr = '${tx.date.day}/${tx.date.month}/${tx.date.year}';
      buffer.writeln(
          '<tr><td>$dateStr</td><td>${tx.description}</td><td>\$${tx.amount.toStringAsFixed(2)}</td></tr>');
    }

    buffer.writeln('</table></body></html>');
    return buffer.toString();
  }
}
